--- # https://poggit.pmmp.io/ci/BlockHorizons/libgeom/~
projects:
  libgeom:
    path: libgeom
    type: library
    model: virion
    libs:
      - src: SOF3/toomuchbuffer/toomuchbuffer
        version: "^1.0"
...
